base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from users.views import Dashboard, HomePage, NewUserRegister, UserProfile

urlpatterns = [
    path("admin/", admin.site.urls),
    path("register/", NewUserRegister.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("profile/", UserProfile.as_view(), name="profile"),
    path("", HomePage.as_view(), name="home"),
    path("dashboard/", Dashboard.as_view(), name="dashboard"),
    path("todo/", include("todo.urls", namespace="todo")),
    path("medialibrary/", include("medialibrary.urls", namespace="medialibrary")),
    path("", include("car_maintenance.urls", namespace="cars")),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_maintenance/urls.py
from django.urls import path

from car_maintenance.views.car.create import CarCreateView
from car_maintenance.views.car.delete import CarDeleteView
from car_maintenance.views.car.detail import CarDetailView
from car_maintenance.views.car.list import CarListView
from car_maintenance.views.car.update import CarUpdateView
from .dash import app

app_name = "car_maintenance"

urlpatterns = [
    path('cars/', CarListView.as_view(), name='car-list'),
    path('cars/new/', CarCreateView.as_view(), name='car-create'),
    path('cars/<int:pk>/update/', CarUpdateView.as_view(), name='car-update'),
    path("cars/<int:pk>/delete/", CarDeleteView.as_view(), name="car-delete"),
    path("cars/<int:pk>/", CarDetailView.as_view(), name="car-detail"),
]

car_maintenance/models.py
from django.db import models
from datetime import datetime
from django.utils.timezone import now


class Car(models.Model):
    carmake = models.CharField(max_length=100)
    carmodel = models.CharField(max_length=100)
    year_of_production = models.DateField()
    #owner=user

    def __str__(self) -> str:
        return f"{self.carmake} {self.carmodel} {self.year_of_production}"


class CarMaintenanceHistory(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='maintenancehistory')
    date = models.DateField(default=now)
    service = models.CharField(max_length=100)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.date} - {self.service} - ${self.cost}"


class FuelCosts(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    date = models.DateField()
    fuelamount = models.DecimalField(max_digits=5, decimal_places=2, help_text="in litres")
    fuelcost = models.DecimalField(max_digits=10, decimal_places=2)
    odometer_reading = models.IntegerField(help_text="total mileage in kilometers", null=True, blank=True)

    def __str__(self):
        return f"{self.date} - {self.fuelamount}L - ${self.fuelcost}"

car_maintenance/forms.py
from bootstrap_datepicker_plus.widgets import DatePickerInput, YearPickerInput
from django import forms

from .models import Car, CarMaintenanceHistory, FuelCosts


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = [
            "carmake",
            "carmodel",
            "year_of_production",
        ]
        widgets = {"year_of_production": YearPickerInput()}


class CarMaintenanceForm(forms.ModelForm):
    class Meta:
        model = CarMaintenanceHistory
        fields = [
            "car",
            "date",
            "service",
            "cost",
            "description",
        ]
        widgets = {"date": DatePickerInput()}


class FuelCostsForm(forms.ModelForm):
    class Meta:
        model = FuelCosts
        fields = [
            "car",
            "date",
            "fuelamount",
            "fuelcost",
            "odometer_reading",
        ]
        widgets = {"date": DatePickerInput()}

car_maintenance/templates/car_maintenance/car_delete_confirm.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="content-section">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <fieldset class="form group">
                                <h3>Are you sure you want to delete the {{ car.car_model }}?</h3>
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-danger" type="submit">Yes</button>
                                <a class="btn btn-secondary" href="{% url 'cars:car-list' car.id %}">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

car_maintenance/templates/car_maintenance/car_detail.html
{% extends "users/index.html" %}
{% load static %}
{% load crispy_forms_tags %}
<head>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
</head>
{% block content %}
    {{ form.media }}
    <div class="card mt-3">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-2">
                <div>
                    <h1 class="mb-0" style="font-style: italic; color: #0a53be;">{{ car.carmake }} {{ car.carmodel }}</h1>
                </div>
            </div>
            {% load plotly_dash %}
            {% plotly_app name="CarMaintenance" %}
            <p class="card-text">wykres kosztów paliwa i napraw per miesiąc</p>
        </div>
    </div>
    <div class="card mt-3">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Car costs
        </div>
        <div class="card-body">
            <table id="datatablesSimple" class="table table-bordered">
                <thead>
                    <tr>
                        <th>Make</th>
                        <th>Model</th>
                        <th>Year of production</th>
                    </tr>
                </thead>
                <tbody>
                    {% for car in objects %}
                        <tr>
                            <td>{{ car.carmake }}</td>
                            <td>{{ car.carmodel }}</td>
                            <td>{{ car.year_of_production.year }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('#datatablesSimple').DataTable({
                "paging": true,
                "ordering": true,
                "info": true
            });
        });
    </script>
{% endblock content %}

car_maintenance/templates/car_maintenance/car_form.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block head %}
<script
  src="https://code.jquery.com/jquery-3.7.1.js"
  integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
  crossorigin="anonymous"></script>
{% endblock head %}
{% block content %}
{{ form.media }}
<h1>Create Car</h1>

<div class="card mt-3">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            {{ form.errors }}

        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
        </form>
    </div>
</div>

{% endblock content %}

car_maintenance/templates/car_maintenance/car_list.html
{% extends "users/index.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="container px-2 d-flex justify-content-between align-items-center">
        <h4 class="display-4 mb-3 fw-semibold" style="color: #0a53be; padding-top: 1.5rem">Cars</h4>
        <div class="d-inline-flex">
            <a href="{% url 'cars:car-create' %}" class="btn btn-secondary mb-3 me-2">Create new car</a>
        </div>
    </div>

    {% for car in cars %}
    <div class="card mb-3">
        <div class="card-body">
            <h3 style="color: #0a53be;">
                <a href="{% url 'cars:car-detail' car.pk %}" class="stylish-link">{{ car.carmake }} {{ car.carmodel }}, {{ car.year_of_production.year }}</a>
            </h3>
            <div class="d-flex justify-content-between">
                <a href="{% url 'cars:car-update' car.pk %}" class="btn btn-warning">Edit</a>
                <form action="{% url 'cars:car-delete' car.pk %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
    {% empty %}
    <p class="lead">No cars available.</p>
    {% endfor %}
</div>
{% endblock content %}