base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from users.views import Dashboard, HomePage, NewUserRegister, UserProfile

urlpatterns = [
    path("admin/", admin.site.urls),
    path("register/", NewUserRegister.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("profile/", UserProfile.as_view(), name="profile"),
    path("", HomePage.as_view(), name="home"),
    path("dashboard/", Dashboard.as_view(), name="dashboard"),
    path("todo/", include("todo.urls", namespace="todo")),
    path("medialibrary/", include("medialibrary.urls", namespace="medialibrary")),
    path("", include("car_maintenance.urls", namespace="cars")),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path

from .views import (
    TaskCategoryCreateView,
    TaskCategoryDeleteView,
    TaskCategoryListView,
    TaskCategoryUpdateView,
    TaskCreateView,
    TaskDeleteView,
    TaskListView,
    TaskUpdateView,
)

app_name = "todo"

urlpatterns = [
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="create-task"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task-category-list/", TaskCategoryListView.as_view(), name="task-category-list"),
    path("task-category/create/", TaskCategoryCreateView.as_view(), name="create-task-category"),
    path("task-category/<int:pk>/update/", TaskCategoryUpdateView.as_view(), name="task-category-update"),
    path("task-category/<int:pk>/delete/", TaskCategoryDeleteView.as_view(), name="task-category-delete"),
]

todo/models.py
from django.contrib.auth.models import User
from django.db import models


class TaskCategory(models.Model):
    category_name = models.CharField(max_length=100, help_text="Name of the task category", unique=True)
    is_default = models.BooleanField(default=False, help_text="Is this a default category?", blank=True)

    def save(self, *args, **kwargs):
        self.category_name = self.category_name.upper()
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.category_name


class Task(models.Model):
    COMPLETE_STATUS_CHOICES = [
        ("TO_DO", "To Do"),
        ("IN_PROGRESS", "In Progress"),
        ("DONE", "Done"),
        ("BLOCKED", "Blocked"),
    ]

    title = models.CharField(max_length=200, help_text="Title of the task")
    completed = models.CharField(max_length=100, choices=COMPLETE_STATUS_CHOICES, help_text="Task status")
    category = models.ForeignKey(TaskCategory, on_delete=models.CASCADE, help_text="Task category")
    created_at = models.DateTimeField(auto_now_add=True, help_text="Date of task create")
    deadline = models.DateTimeField(blank=True, null=True, help_text="Deadline of the task")
    author = models.ForeignKey(User, on_delete=models.CASCADE, help_text="Author of the task")

    def __str__(self):
        return self.title

todo/forms.py
from bootstrap_datepicker_plus.widgets import DateTimePickerInput
from django import forms

from .models import Task, TaskCategory


class TaskForm(forms.ModelForm):
    category = forms.ModelChoiceField(required=True, queryset=TaskCategory.objects.all())
    title = forms.CharField(required=True)
    completed = forms.ChoiceField(required=True, choices=Task.COMPLETE_STATUS_CHOICES)

    class Meta:
        model = Task
        fields = [
            "category",
            "title",
            "completed",
            "deadline",
        ]
        widgets = {"deadline": DateTimePickerInput()}


class TaskCategoryForm(forms.ModelForm):
    category_name = forms.CharField(required=True)
    is_default = forms.BooleanField(required=False)

    class Meta:
        model = TaskCategory
        fields = [
            "category_name",
        ]

todo/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils.functional import cached_property
from django.views.generic import CreateView, DeleteView, ListView, UpdateView
from view_breadcrumbs import CreateBreadcrumbMixin, DetailBreadcrumbMixin, ListBreadcrumbMixin

from .forms import TaskCategoryForm, TaskForm
from .models import Task, TaskCategory


class TaskListView(ListBreadcrumbMixin, LoginRequiredMixin, ListView):
    model = Task
    template_name = "todo/task_list.html"
    add_home = False

    @cached_property
    def crumbs(self):
        breadcrumb_list = [
            ("Dashboard", reverse_lazy("dashboard")),
            ("Tasks", reverse_lazy("todo:task-list")),
        ]
        return breadcrumb_list


class TaskCreateView(CreateBreadcrumbMixin, LoginRequiredMixin, CreateView):
    model = Task
    template_name = "todo/task_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    @cached_property
    def crumbs(self):
        breadcrumb_list = [
            ("Dashboard", reverse_lazy("dashboard")),
            ("Tasks", reverse_lazy("todo:task-list")),
            ("Create task", None),
        ]
        return breadcrumb_list


class TaskUpdateView(DetailBreadcrumbMixin, LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "todo/task_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")

    @cached_property
    def crumbs(self):
        breadcrumb_list = [
            ("Dashboard", reverse_lazy("dashboard")),
            ("Tasks", reverse_lazy("todo:task-list")),
            ("Update task", None),
        ]
        return breadcrumb_list


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


class TaskCategoryListView(ListBreadcrumbMixin, ListView):
    model = TaskCategory
    template_name = "todo/task_category_list.html"
    add_home = False

    @cached_property
    def crumbs(self):
        breadcrumb_list = [
            ("Dashboard", reverse_lazy("dashboard")),
            ("Tasks", reverse_lazy("todo:task-list")),
            ("Tasks category list", reverse_lazy("todo:task-category-list")),
        ]
        return breadcrumb_list


class TaskCategoryCreateView(CreateBreadcrumbMixin, LoginRequiredMixin, CreateView):
    model = TaskCategory
    template_name = "todo/task_category_form.html"
    form_class = TaskCategoryForm
    success_url = reverse_lazy("todo:task-category-list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.category_name = form.instance.category_name.upper()
        return super().form_valid(form)

    @cached_property
    def crumbs(self):
        breadcrumb_list = [
            ("Dashboard", reverse_lazy("dashboard")),
            ("Tasks category list", reverse_lazy("todo:task-category-list")),
            ("Create new category", None),
        ]
        return breadcrumb_list


class TaskCategoryUpdateView(DetailBreadcrumbMixin, LoginRequiredMixin, UpdateView):
    model = TaskCategory
    template_name = "todo/task_category_form.html"
    form_class = TaskCategoryForm
    success_url = reverse_lazy("todo:task-category-list")

    @cached_property
    def crumbs(self):
        breadcrumb_list = [
            ("Dashboard", reverse_lazy("dashboard")),
            ("Tasks category list", reverse_lazy("todo:task-category-list")),
            ("Update category", None),
        ]
        return breadcrumb_list


class TaskCategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = TaskCategory
    success_url = reverse_lazy("todo:task-category-list")

todo/templates/todo/task_category_form.html
{% extends "users/index.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Create New Task Category</h1>
    <div class="card mt-3">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                {{ form.errors }}
                <div class="mt-3">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

todo/templates/todo/task_category_list.html
{% extends "users/index.html" %}
{% load static %}

{% block content %}
    <div class="container px-2 d-flex justify-content-between align-items-center">
        <h4 class="display-4 mb-3 fw-semibold" style="color: #0a53be; padding-top: 1.5rem">Task Categories</h4>
        <a href="{% url 'todo:create-task-category' %}" class="btn btn-secondary mb-3">Create new category</a>
    </div>

    {% for task_category in object_list %}
    <div class="card mb-3" style="background-color: #D4D9DB;">
        <div class="card-body">
            <h5 class="card-title font-weight-bold">{{ task_category.category_name }}</h5>

            <div class="d-flex justify-content-between">
                <a href="{% url 'todo:task-category-update' task_category.pk %}" class="btn btn-warning">Edit</a>
                <form action="{% url 'todo:task-category-delete' task_category.pk %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
    {% empty %}
    <p class="lead">No categories available.</p>
    {% endfor %}

{% endblock content %}

todo/templates/todo/task_form.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block head %}
<script
  src="https://code.jquery.com/jquery-3.7.1.js"
  integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
  crossorigin="anonymous"></script>
{% endblock head %}
{% block content %}
{{ form.media }}
<h1>Create Task</h1>

<div class="card mt-3">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            {{ form.errors }}

        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
        </form>
    </div>
</div>

{% endblock content %}

todo/templates/todo/task_list.html
{% extends "users/index.html" %}
{% load static %}

{% block head %}
    <style>
    .TO_DO {
        background-color: lightgoldenrodyellow;
    }

    .IN_PROGRESS {
        background-color: lightblue;
    }
    .DONE {
        background-color: lightgreen;
    }
    .BLOCKED {
        background-color: lightcoral;
    }

    </style>
{% endblock head %}
{% block content %}
<div class="container">
    <div class="container px-2 d-flex justify-content-between align-items-center">
        <h4 class="display-4 mb-3 fw-semibold" style="color: #0a53be; padding-top: 1.5rem">Tasks</h4>
        <div class="d-inline-flex">
            <a href="{% url 'todo:create-task' %}" class="btn btn-secondary mb-3 me-2">Create new task</a>
            <a href="{% url 'todo:task-category-list' %}" class="btn btn-primary mb-3">Go to task categories</a>
        </div>
    </div>


    {% for task in object_list %}
    <div class="card mb-3 {{ task.completed }}">
        <div class="card-body">
            <h5 class="card-title font-weight-bold">{{ task.title }}</h5>
            <p class="card-text small">
                <span><b>Created:</b> {{ task.created_at }}</span>
                <span class="mx-2"><b>Category:</b> {{ task.category.category_name }}</span>
                <span><b>Status:</b> {{ task.get_completed_display }}</span>
            </p>
            {% if task.deadline %}
            <p class="card-text small"><b>Deadline:</b> {{ task.deadline }}</p>
            {% endif %}
            <div class="d-flex justify-content-between">
                <a href="{% url 'todo:task-update' task.pk %}" class="btn btn-warning">Edit</a>
                <form action="{% url 'todo:task-delete' task.pk %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
    {% empty %}
    <p class="lead">No tasks available.</p>
    {% endfor %}
</div>
{% endblock content %}