base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from users.views import Dashboard, HomePage, NewUserRegister, UserProfile

urlpatterns = [
    path("admin/", admin.site.urls),
    path("register/", NewUserRegister.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("profile/", UserProfile.as_view(), name="profile"),
    path("", HomePage.as_view(), name="home"),
    path("dashboard/", Dashboard.as_view(), name="dashboard"),
    path("todo/", include("todo.urls", namespace="todo")),
    path("medialibrary/", include("medialibrary.urls", namespace="medialibrary")),
    path("", include("car_maintenance.urls", namespace="cars")),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_maintenance/urls.py
from django.urls import path

from car_maintenance.views.car.create import CarCreateView
from car_maintenance.views.car.delete import CarDeleteView
from car_maintenance.views.car.detail import CarDetailView
from car_maintenance.views.car.list import CarListView
from car_maintenance.views.car.update import CarUpdateView
from .dash import app

app_name = "car_maintenance"

urlpatterns = [
    path('cars/', CarListView.as_view(), name='car-list'),
    path('cars/new/', CarCreateView.as_view(), name='car-create'),
    path('cars/<int:pk>/update/', CarUpdateView.as_view(), name='car-update'),
    path("cars/<int:pk>/delete/", CarDeleteView.as_view(), name="car-delete"),
    path("cars/<int:pk>/", CarDetailView.as_view(), name="car-detail"),
]

medialibrary/urls.py
from django.urls import path

from medialibrary.views.author.create import BookAuthorCreateView
from medialibrary.views.author.delete import BookAuthorDeleteView
from medialibrary.views.author.detail import BookAuthorDetailView
from medialibrary.views.author.update import BookAuthorUpdateView
from medialibrary.views.book.create import BookCreateView
from medialibrary.views.book.delete import BookDeleteView
from medialibrary.views.book.detail import BookDetailView
from medialibrary.views.book.list import BookListView
from medialibrary.views.book.update import BookUpdateView
from medialibrary.views.mainpage import MedialibraryMainPage
from medialibrary.views.movie.create import MovieCreateView
from medialibrary.views.movie.delete import MovieDeleteView
from medialibrary.views.movie.detail import MovieDetailView
from medialibrary.views.movie.list import MovieListView
from medialibrary.views.movie.update import MovieUpdateView

app_name = "medialibrary"

urlpatterns = [
    path("", MedialibraryMainPage.as_view(), name="medialibrary"),
    path("authors/new/", BookAuthorCreateView.as_view(), name="create-author"),
    path("authors/<int:pk>/update", BookAuthorUpdateView.as_view(), name="author-update"),
    path("authors/<int:pk>/", BookAuthorDetailView.as_view(), name="author-detail"),
    path("authors/<int:pk>/delete/", BookAuthorDeleteView.as_view(), name="author-delete"),
    path("books/", BookListView.as_view(), name="book-list"),
    path("books/new/", BookCreateView.as_view(), name="create-book"),
    path("books/<int:pk>/update", BookUpdateView.as_view(), name="book-update"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("books/<int:pk>/delete/", BookDeleteView.as_view(), name="book-delete"),
    path("movies/", MovieListView.as_view(), name="movie-list"),
    path("movies/new/", MovieCreateView.as_view(), name="create-movie"),
    path("movies/<int:pk>/update", MovieUpdateView.as_view(), name="movie-update"),
    path("movies/<int:pk>/", MovieDetailView.as_view(), name="movie-detail"),
    path("movies/<int:pk>/delete/", MovieDeleteView.as_view(), name="movie-delete"),
]

todo/urls.py
from django.urls import path

from .views import (
    TaskCategoryCreateView,
    TaskCategoryDeleteView,
    TaskCategoryListView,
    TaskCategoryUpdateView,
    TaskCreateView,
    TaskDeleteView,
    TaskListView,
    TaskUpdateView,
)

app_name = "todo"

urlpatterns = [
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="create-task"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task-category-list/", TaskCategoryListView.as_view(), name="task-category-list"),
    path("task-category/create/", TaskCategoryCreateView.as_view(), name="create-task-category"),
    path("task-category/<int:pk>/update/", TaskCategoryUpdateView.as_view(), name="task-category-update"),
    path("task-category/<int:pk>/delete/", TaskCategoryDeleteView.as_view(), name="task-category-delete"),
]

users/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="profile_pics/default.png", upload_to="profile_pics")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 400 or img.width > 400:
            output_size = (400, 400)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def __str__(self):
        return f"Profile of {self.user.username}"

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    error_messages = {
        "password_mismatch": "The two password fields didn't match.",
    }
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput,
        help_text="Enter the same password as above, for verification.",
    )
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages["password_mismatch"],
                code="password_mismatch",
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email"]

users/views.py
from django.contrib import messages
from django.contrib.auth import logout as auth_logout
from django.shortcuts import redirect, render
from django.views import View

from .forms import CustomUserCreationForm, UserUpdateForm


class NewUserRegister(View):
    template_name: str = "users/register.html"

    def get(self, request) -> render:
        form = CustomUserCreationForm()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Account's been created for {username}!")
            return redirect("login")
        return render(request, self.template_name, {"form": form})


class LogoutUser(View):
    def get(self, request) -> redirect:
        auth_logout(request)

        message: str = "You have been successfully logged out"
        messages.success(request, message)

        return redirect("home")


class HomePage(View):
    template_name = "users/landing_page.html"

    def get(self, request) -> redirect:
        return render(request, self.template_name)


class UserProfile(View):
    template_name: str = "users/profile.html"

    def get(self, request) -> render:
        user_form = UserUpdateForm(instance=request.user)
        return render(request, self.template_name, {"user_form": user_form})

    def post(self, request):
        user_form = UserUpdateForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, "Your profile has been updated")
            return redirect("profile")
        messages.error(request, "There was an error updating your profile")
        return redirect("profile")


class Dashboard(View):
    template_name = "users/dashboard.html"

    def get(self, request) -> redirect:
        return render(request, self.template_name)

users/templates/users/dashboard.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg">
                <div class="card border-0 rounded-lg mt-5">
                    <div class="content-section">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-xl-3 col-md-6">
                                    <div class="card mb-4 border-0">
                                        <div class="card-body d-flex justify-content-center align-items-center">
                                            <div class="p-4">
                                                <img class="img-fluid" src="/static/home_page/budget.png" alt="Can't load image" style="width: 150px; height: 150px;" />
                                            </div>
                                        </div>
                                        <div class="card-footer bg-secondary d-flex align-items-center justify-content-between">
                                            <a class="small text-white stretched-link" href="#" style="text-decoration: none;">Budget management</a>
                                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-md-6">
                                    <div class="card mb-4 border-0">
                                        <div class="card-body d-flex justify-content-center align-items-center">
                                            <div class="p-4">
                                                <img class="img-fluid" src="/static/home_page/expenses.png" alt="Can't load image" style="width: 150px; height: 150px;" />
                                            </div>
                                        </div>
                                        <div class="card-footer bg-secondary d-flex align-items-center justify-content-between">
                                            <a class="small text-white stretched-link" href="#" style="text-decoration: none;">Expense tracking</a>
                                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-md-6">
                                    <div class="card mb-4 border-0">
                                        <div class="card-body d-flex justify-content-center align-items-center">
                                            <div class="p-4">
                                                <img class="img-fluid" src="/static/home_page/car_costs.png" alt="Can't load image" style="width: 150px; height: 150px;" />
                                            </div>
                                        </div>
                                        <div class="card-footer bg-secondary d-flex align-items-center justify-content-between">
                                            <a class="small text-white stretched-link" href="{% url 'cars:car-list' %}" style="text-decoration: none;">Car maintenance cost calculator</a>
                                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-md-6">
                                    <div class="card mb-4 border-0">
                                        <div class="card-body d-flex justify-content-center align-items-center">
                                            <div class="p-4">
                                                <img class="img-fluid" src="/static/home_page/libraries.png" alt="Can't load image" style="width: 150px; height: 150px;" />
                                            </div>
                                        </div>
                                        <div class="card-footer bg-secondary d-flex align-items-center justify-content-between">
                                            <a class="small text-white stretched-link" href="{% url 'medialibrary:medialibrary' %}" style="text-decoration: none;">Movie and book library</a>
                                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-md-6">
                                    <div class="card mb-4 border-0">
                                        <div class="card-body d-flex justify-content-center align-items-center">
                                            <div class="p-4">
                                                <img class="img-fluid" src="/static/home_page/to_do.png" alt="Can't load image" style="width: 150px; height: 150px;" />
                                            </div>
                                        </div>
                                        <div class="card-footer bg-secondary d-flex align-items-center justify-content-between">
                                            <a class="small text-white stretched-link" href="{% url 'todo:task-list' %}" style="text-decoration: none;">To-do list</a>
                                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/index.html
{% load static %}
{% load view_breadcrumbs %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Life assist</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        {% block head %} {% endblock head %}
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="{% url 'dashboard' %}" rel="stylesheet">Life assist</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'register' %}">Settings</a></li>
                        <li><a class="dropdown-item" href="{% url 'register' %}">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{% url 'home' %}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="{% url 'dashboard' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <div class="sb-sidenav-menu-heading">Apps</div>
                            <a class="nav-link" href="{% url 'cars:car-list' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Budget management
                            </a>
                            <a class="nav-link" href="{% url 'cars:car-list' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Expense tracking
                            </a>
                            <a class="nav-link" href="{% url 'cars:car-list' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Car maintenance cost calculator
                            </a>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLibrary" aria-expanded="false" aria-controls="collapseLibrary">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Movie and book library
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLibrary" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="{% url 'medialibrary:book-list' %}">Book Library</a>
                                    <a class="nav-link" href="{% url 'medialibrary:movie-list' %}">Movie Library</a>
                                </nav>
                            </div>
                            <a class="nav-link" href="{% url 'todo:task-list' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                To-Do list
                            </a>
                            <div class="sb-sidenav-menu-heading">Profile</div>
                            <a class="nav-link" href="{% url 'profile' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                User profile
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        {{ user.username }}
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <div class="container-fluid px-4" style="padding-top: 1.5em;">
                            {% block breadcrumbs %}
                                {% render_breadcrumbs 'users/view_breadcrumbs.html' %}
                            {% endblock %}
                        </div>
                        {% block content %}
                        {% endblock content %}
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Life Assist 2024</div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
    </body>
</html>

users/templates/users/landing_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Life assist</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="#page-top">Life assist</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Sign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Log In</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="masthead text-center text-black">
            <div class="masthead-content">
                <div class="container px-5">
                    <h1 class="display-2 mb-3 fw-semibold" style="color: #0a53be; padding-top: 1.5rem">Life assist</h1>
                    <h2 class="display-5 mb-0">App to digitalized your life</h2>
                </div>
            </div>
        </header>
        <!-- Content section 1-->
        <section id="scroll">
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6 order-lg-2">
                        <div class="p-5"><img class="img-fluid" src="/static/home_page/budget.png" alt="Can't load image" style="width: 150px; height: 150px" /></div>
                    </div>
                    <div class="col-lg-6 order-lg-1">
                        <div class="p-5">
                            <h2 class="display-6 fw-semibold" style="color: #0a53be;">Budget management</h2>
                            <p>Application that helps you control your finances by planning budgets and generating financial reports.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Content section 2-->
        <section>
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6">
                        <div class="p-5 text-lg-end"><img class="img-fluid" src="/static/home_page/expenses.png" alt="Can't load image" style="width: 150px; height: 150px" /></div>
                    </div>
                    <div class="col-lg-6">
                        <div class="p-5">
                            <h2 class="display-6 fw-semibold" style="color: #0a53be;">Expense tracking</h2>
                            <p>Tool that allows you to monitor all expenses in one place. It makes it easy to track your finances and analyze where your money is going.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Content section 3-->
        <section>
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6 order-lg-2">
                        <div class="p-5"><img class="img-fluid" src="/static/home_page/car_costs.png" alt="Can't load image" style="width: 150px; height: 150px" /></div>
                    </div>
                    <div class="col-lg-6 order-lg-1">
                        <div class="p-5">
                            <h2 class="display-6 fw-semibold" style="color: #0a53be;">Car maintenance cost calculator</h2>
                            <p>Application that assists in managing the costs associated with maintaining a car. It helps track expenses on fuel, repairs, technical inspections, and other vehicle-related expenses.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Content section 4-->
        <section>
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6">
                        <div class="p-5 text-lg-end"><img class="img-fluid rounded-circle" src="/static/home_page/libraries.png" alt="Can't load image" style="width: 150px; height: 150px" /></div>
                    </div>
                    <div class="col-lg-6">
                        <div class="p-5">
                            <h2 class="display-6 fw-semibold" style="color: #0a53be;">Movie and book library</h2>
                            <p>An online library where you can store and manage your collection of movies and books. It allows you to add, search, and rate items, as well as create a list of favorite titles.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Content section 5-->
        <section>
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6 order-lg-2">
                        <div class="p-5"><img class="img-fluid" src="/static/home_page/to_do.png" alt="Can't load image" style="width: 150px; height: 150px" /></div>
                    </div>
                    <div class="col-lg-6 order-lg-1">
                        <div class="p-5">
                            <h2 class="display-6 fw-semibold" style="color: #0a53be;">To-do list</h2>
                            <p>To-do list is an application for creating a list of tasks to be completed. It allows you to add, remove, and edit tasks, as well as set deadlines for their completion.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Life assist 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

users/templates/users/view_breadcrumbs.html
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    {% for url, label in breadcrumbs %}
      {% if not url or forloop.counter == breadcrumbs_total %}
        <li class="breadcrumb-item{% if forloop.counter == breadcrumbs_total %} active{% endif %}" {% if forloop.counter == breadcrumbs_total %}aria-current="page"{% endif %}>{{ label|safe }}</li>
      {% else %}
        <li class="breadcrumb-item"><a href="{{ url }}">{{ label|safe }}</a></li>
      {% endif %}
    {% endfor %}
  </ol>
</nav>