base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from users.views import Dashboard, HomePage, NewUserRegister, UserProfile

urlpatterns = [
    path("admin/", admin.site.urls),
    path("register/", NewUserRegister.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("profile/", UserProfile.as_view(), name="profile"),
    path("", HomePage.as_view(), name="home"),
    path("dashboard/", Dashboard.as_view(), name="dashboard"),
    path("todo/", include("todo.urls", namespace="todo")),
    path("medialibrary/", include("medialibrary.urls", namespace="medialibrary")),
    path("", include("car_maintenance.urls", namespace="cars")),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medialibrary/urls.py
from django.urls import path

from medialibrary.views.author.create import BookAuthorCreateView
from medialibrary.views.author.delete import BookAuthorDeleteView
from medialibrary.views.author.detail import BookAuthorDetailView
from medialibrary.views.author.update import BookAuthorUpdateView
from medialibrary.views.book.create import BookCreateView
from medialibrary.views.book.delete import BookDeleteView
from medialibrary.views.book.detail import BookDetailView
from medialibrary.views.book.list import BookListView
from medialibrary.views.book.update import BookUpdateView
from medialibrary.views.mainpage import MedialibraryMainPage
from medialibrary.views.movie.create import MovieCreateView
from medialibrary.views.movie.delete import MovieDeleteView
from medialibrary.views.movie.detail import MovieDetailView
from medialibrary.views.movie.list import MovieListView
from medialibrary.views.movie.update import MovieUpdateView

app_name = "medialibrary"

urlpatterns = [
    path("", MedialibraryMainPage.as_view(), name="medialibrary"),
    path("authors/new/", BookAuthorCreateView.as_view(), name="create-author"),
    path("authors/<int:pk>/update", BookAuthorUpdateView.as_view(), name="author-update"),
    path("authors/<int:pk>/", BookAuthorDetailView.as_view(), name="author-detail"),
    path("authors/<int:pk>/delete/", BookAuthorDeleteView.as_view(), name="author-delete"),
    path("books/", BookListView.as_view(), name="book-list"),
    path("books/new/", BookCreateView.as_view(), name="create-book"),
    path("books/<int:pk>/update", BookUpdateView.as_view(), name="book-update"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("books/<int:pk>/delete/", BookDeleteView.as_view(), name="book-delete"),
    path("movies/", MovieListView.as_view(), name="movie-list"),
    path("movies/new/", MovieCreateView.as_view(), name="create-movie"),
    path("movies/<int:pk>/update", MovieUpdateView.as_view(), name="movie-update"),
    path("movies/<int:pk>/", MovieDetailView.as_view(), name="movie-detail"),
    path("movies/<int:pk>/delete/", MovieDeleteView.as_view(), name="movie-delete"),
]

todo/urls.py
from django.urls import path

from .views import (
    TaskCategoryCreateView,
    TaskCategoryDeleteView,
    TaskCategoryListView,
    TaskCategoryUpdateView,
    TaskCreateView,
    TaskDeleteView,
    TaskListView,
    TaskUpdateView,
)

app_name = "todo"

urlpatterns = [
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="create-task"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task-category-list/", TaskCategoryListView.as_view(), name="task-category-list"),
    path("task-category/create/", TaskCategoryCreateView.as_view(), name="create-task-category"),
    path("task-category/<int:pk>/update/", TaskCategoryUpdateView.as_view(), name="task-category-update"),
    path("task-category/<int:pk>/delete/", TaskCategoryDeleteView.as_view(), name="task-category-delete"),
]

medialibrary/models.py
from django.db import models


class BookAuthor(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name} {self.surname}"


class Book(models.Model):
    RATING_CHOICES = [
        ("Terrible", "Terrible"),
        ("Bad", "Bad"),
        ("Okay", "Okay"),
        ("Really good!", "Really good!"),
        ("New favorite!", "New favorite!"),
    ]

    title = models.CharField(max_length=200)
    author = models.ForeignKey(BookAuthor, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    published_date = models.DateField(null=True, blank=True)
    summary = models.TextField(null=True, blank=True)
    rating = models.CharField(null=True, blank=True, max_length=100, choices=RATING_CHOICES)
    tom = models.IntegerField(null=True, blank=True)
    series_name = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.title


class Movie(models.Model):
    RATING_CHOICES = [
        ("Terrible", "Terrible"),
        ("Bad", "Bad"),
        ("Okay", "Okay"),
        ("Really good!", "Really good!"),
        ("New favorite!", "New favorite!"),
    ]

    title = models.CharField(max_length=200)
    director = models.CharField(max_length=100, null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)
    summary = models.TextField(null=True, blank=True)
    rating = models.CharField(max_length=100, choices=RATING_CHOICES, null=True, blank=True)

medialibrary/forms.py
from bootstrap_datepicker_plus.widgets import YearPickerInput
from django import forms

from .models import Book, BookAuthor, Movie


class BookAuthorForm(forms.ModelForm):
    class Meta:
        model = BookAuthor
        fields = [
            "name",
            "surname",
        ]


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            "title",
            "author",
            "published_date",
            "summary",
            "rating",
        ]
        widgets = {"published_date": YearPickerInput()}


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = [
            "title",
            "director",
            "release_date",
            "summary",
            "rating",
        ]
        widgets = {"release_date": YearPickerInput()}

medialibrary/views/mainpage.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils.functional import cached_property
from django.views.generic import TemplateView
from view_breadcrumbs import BaseBreadcrumbMixin


class MedialibraryMainPage(BaseBreadcrumbMixin, LoginRequiredMixin, TemplateView):
    template_name = "medialibrary/medialibrary_main_page.html"

    @cached_property
    def crumbs(self):
        breadcrumb_list = [
            ("Dashboard", reverse_lazy("dashboard")),
            ("Medialibrary", None),
        ]
        return breadcrumb_list

medialibrary/templates/medialibrary/book_delete_confirm.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="content-section">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <fieldset class="form group">
                                <h3>Are you sure you want to delete the {{ book.title }}?</h3>
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-danger" type="submit">Yes</button>
                                <a class="btn btn-secondary" href="{% url 'medialibrary:book-detail' book.id %}">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

medialibrary/templates/medialibrary/book_detail.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}
<div class="card mt-3">
    <div class="card-body">
        <div class="d-flex justify-content-between align-items-center mb-2">
            <div>
                <h1 class="mb-0" style="font-style: italic;">{{ book.title }}</h1>
                <p class="mb-0"><small class="text-muted">{{ book.author }}, {{ book.published_date.year }}</small></p>
            </div>
            <div>
                <a href="{% url 'medialibrary:book-update' book.id %}" class="btn btn-secondary">Edit</a>
                <a href="{% url 'medialibrary:book-delete' book.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
        <p class="card-text">{{ book.summary }}</p>
        <p class="card-text"><small class="text-bg-dark">Rating: {{ book.rating }}</small></p>
    </div>
</div>
{% endblock content %}

medialibrary/templates/medialibrary/book_form.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block head %}
<script
  src="https://code.jquery.com/jquery-3.7.1.js"
  integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
  crossorigin="anonymous"></script>
{% endblock head %}
{% block content %}
{{ form.media }}
<h1>Create Book</h1>

<div class="card mt-3">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            {{ form.errors }}

        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
        </form>
    </div>
</div>

{% endblock content %}

medialibrary/templates/medialibrary/book_list.html
{% extends "users/index.html" %}
{% load static %}

<head>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
</head>

{% block content %}
<div class="container">
    <div class="px-2 d-flex justify-content-between align-items-center">
        <h4 class="display-4 mb-3 fw-semibold" style="color: #0a53be; padding-top: 1.5rem">Books</h4>
        <div class="d-inline-flex">
            <a href="{% url 'medialibrary:create-book' %}" class="btn btn-secondary mb-3 me-2">Add new book</a>
            <a href="{% url 'medialibrary:create-author' %}" class="btn btn-secondary mb-3 me-2">Add new author</a>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-lg">
            <div class="card shadow-lg border-0 rounded-lg mt-3">
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Books library
                    </div>
                    <div class="card-body">
                        <table id="datatablesSimple">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Author</th>
                                    <th>Year</th>
                                    <th>Summary</th>
                                    <th>Rating</th>
                                    <th>Tom number</th>
                                    <th>Series Name</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for book in books %}
                                <tr>
                                    <td><a href="{% url 'medialibrary:book-detail' book.pk %}">{{ book.title }}</a></td>
                                    <td><a href="{% url 'medialibrary:author-detail' book.author.pk %}">{{ book.author }}</a></td>
                                    <td>{{ book.published_date.year }}</td>
                                    <td>{{ book.summary }}</td>
                                    <td>{{ book.rating }}</td>
                                    <td>{{ book.tom }}</td>
                                    <td>{{ book.series_name }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
    $('#datatablesSimple').DataTable({
        "paging": true,
        "ordering": true,
        "info": true
    });
});
</script>
{% endblock content %}

medialibrary/templates/medialibrary/book_list_v2.html
{% extends "users/index.html" %}
{% load static %}

<head>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
</head>

{% block content %}
<div class="container">
    <div class="px-2 d-flex justify-content-between align-items-center">
        <h4 class="display-4 mb-3 fw-semibold" style="color: #0a53be; padding-top: 1.5rem">Books</h4>
        <div class="d-inline-flex">
            <a href="{% url 'medialibrary:create-book' %}" class="btn btn-secondary mb-3 me-2">Add new book</a>
            <a href="{% url 'todo:task-category-list' %}" class="btn btn-primary mb-3">Go to task categories</a>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-lg">
            <div class="card shadow-lg border-0 rounded-lg mt-3">
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Books library
                    </div>
                    <div class="card-body">
                        <table id="datatablesSimple">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Author</th>
                                    <th>Year</th>
                                    <th>Summary</th>
                                    <th>Rating</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for book in books %}
                                <tr>
                                    <td><a href="{% url 'medialibrary:book-update' book.pk %}">{{ book.title }}</a></td>
                                    <td>{{ book.author }}</td>
                                    <td>{{ book.published_date.year }}</td>
                                    <td>{{ book.summary }}</td>
                                    <td>{{ book.rating }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
    $('#datatablesSimple').DataTable({
        "paging": true,
        "ordering": true,
        "info": true
    });
});
</script>
{% endblock content %}

medialibrary/templates/medialibrary/bookauthor_delete_confirm.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="content-section">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <fieldset class="form group">
                                <h3>Are you sure you want to delete the {{ bookauthor }}?</h3>
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-danger" type="submit">Yes</button>
                                <a class="btn btn-secondary" href="{% url 'medialibrary:book-detail' bookauthor.id %}">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

medialibrary/templates/medialibrary/bookauthor_detail.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}
<div class="card mt-3">
    <div class="card-body">
        <div class="d-flex justify-content-between align-items-center mb-2">
            <div>
                <h1 class="mb-0" style="font-style: italic;">{{ bookauthor.name }} {{ bookauthor.surname }}</h1>
            </div>
            <div>
                <a href="{% url 'medialibrary:author-update' bookauthor.id %}" class="btn btn-secondary">Edit</a>
                <a href="{% url 'medialibrary:author-delete' bookauthor.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

medialibrary/templates/medialibrary/bookauthor_form.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block head %}
<script
  src="https://code.jquery.com/jquery-3.7.1.js"
  integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
  crossorigin="anonymous"></script>
{% endblock head %}
{% block content %}
{{ form.media }}
<h1>Create Author</h1>

<div class="card mt-3">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            {{ form.errors }}

        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
        </form>
    </div>
</div>

{% endblock content %}

medialibrary/templates/medialibrary/medialibrary_main_page.html
{% extends "users/index.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg">
                <div class="card border-0 rounded-lg mt-5">
                    <div class="content-section">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-xl-3 col-md-6">
                                    <div class="card mb-4 border-0">
                                        <div class="card-body d-flex justify-content-center align-items-center">
                                            <div class="p-4">
                                                <img class="img-fluid" src="/static/medialibrary/book_library.png" alt="Can't load image" style="width: 150px; height: 150px;" />
                                            </div>
                                        </div>
                                        <div class="card-footer bg-secondary d-flex align-items-center justify-content-between">
                                            <a class="small text-white stretched-link" href="{% url 'medialibrary:book-list' %}" style="text-decoration: none;">Book library</a>
                                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-md-6">
                                    <div class="card mb-4 border-0">
                                        <div class="card-body d-flex justify-content-center align-items-center">
                                            <div class="p-4">
                                                <img class="img-fluid" src="/static/medialibrary/movie_library.png" alt="Can't load image" style="width: 150px; height: 150px;" />
                                            </div>
                                        </div>
                                        <div class="card-footer bg-secondary d-flex align-items-center justify-content-between">
                                            <a class="small text-white stretched-link" href="{% url 'medialibrary:movie-list' %}" style="text-decoration: none;">Movie library</a>
                                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

medialibrary/templates/medialibrary/movie_delete_confirm.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="content-section">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <fieldset class="form group">
                                <h3>Are you sure you want to delete the {{ movie.title }}?</h3>
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-danger" type="submit">Yes</button>
                                <a class="btn btn-secondary" href="{% url 'medialibrary:movie-detail' movie.id %}">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

medialibrary/templates/medialibrary/movie_detail.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}
<div class="card mt-3">
    <div class="card-body">
        <div class="d-flex justify-content-between align-items-center mb-2">
            <div>
                <h1 class="mb-0" style="font-style: italic;">{{ movie.title }}</h1>
                <p class="mb-0"><small class="text-muted">{{ movie.director }}, {{ movie.release_date.year }}</small></p>
            </div>
            <div>
                <a href="{% url 'medialibrary:movie-update' movie.id %}" class="btn btn-secondary">Edit</a>
                <a href="{% url 'medialibrary:movie-delete' movie.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
        <p class="card-text">{{ movie.summary }}</p>
        <p class="card-text"><small class="text-bg-dark">Rating: {{ movie.rating }}</small></p>
    </div>
</div>
{% endblock content %}

medialibrary/templates/medialibrary/movie_form.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block head %}
<script
  src="https://code.jquery.com/jquery-3.7.1.js"
  integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
  crossorigin="anonymous"></script>
{% endblock head %}
{% block content %}
{{ form.media }}
<h1>Create Movie</h1>

<div class="card mt-3">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            {{ form.errors }}

        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
        </form>
    </div>
</div>

{% endblock content %}

medialibrary/templates/medialibrary/movie_list.html
{% extends "users/index.html" %}
{% load static %}

<head>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
</head>

{% block content %}
<div class="container">
    <div class="px-2 d-flex justify-content-between align-items-center">
        <h4 class="display-4 mb-3 fw-semibold" style="color: #0a53be; padding-top: 1.5rem">Movies</h4>
        <div class="d-inline-flex">
            <a href="{% url 'medialibrary:create-movie' %}" class="btn btn-secondary mb-3 me-2">Add new movie</a>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-lg">
            <div class="card shadow-lg border-0 rounded-lg mt-3">
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Movies library
                    </div>
                    <div class="card-body">
                        <table id="datatablesSimple">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Director</th>
                                    <th>Premiere</th>
                                    <th>Summary</th>
                                    <th>Rating</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for movie in movies %}
                                <tr>
                                    <td><a href="{% url 'medialibrary:movie-detail' movie.pk %}">{{ movie.title }}</a></td>
                                    <td>{{ movie.director }}</td>
                                    <td>{{ movie.release_date.year }}</td>
                                    <td>{{ movie.summary }}</td>
                                    <td>{{ movie.rating }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
    $('#datatablesSimple').DataTable({
        "paging": true,
        "ordering": true,
        "info": true
    });
});
</script>
{% endblock content %}